---
title: Uncollected Pages
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: tech. design. games. food. life. psycosis.
url: https://blog.alokprateek.ml/
permalink: ":title/"
baseurl: ''
markdown: kramdown
highlight: rouge
sass:
  style: compressed
compress_html:
  clippings:
  - html
  - div
  - p
  - ul
  - td
  - h1
  - h2
  - h3
  - h4
  - link
  - meta
  - footer
  - nav
  - img
  - header
  - hr
  - br
  - head
  - style
  - li
  - ul
  - ol
  - time
  - main
  - script
  - title
  comments:
  - "<!-- "
  - " -->"
  endings:
  - all
  ignore:
    envs:
    - local
  blanklines: false
  profile: false
  startings: []
analytics: UA-85177250-1
disqus-shortname: oxyenyos
api-token: 
include:
- _pages
version: 0.9
paginate: 6
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-seo-tag
